### ISSUE TITLE
[Errno 2] No such file or directory: 'model_manager_cifar10.tst'

### ISSUE THREAD

**Issue by maomaoyuchengzi** [antspy/quantized_distillation#2]
what is 'model_manager_cifar10.tst',and where i can download?

**Comment by antspy** [comment]
It is just a file created by the ModelManager class. It is where the model manager is saved, and holds the informations about which models have been trained, where are they saved, etc.

The first time you run the code, you need to create the model manager instance with the option  create_new_model_manager= True. This will create the model_manager_cifar10.tst file. For successive runs, you need to put create_new_model_manager= False, and the file model_manager_cifar10.tst will be used.

This is done intentionally because if you accidentally overwrite your model manager you will have catastrophic loss of information, so I try to make it harder to do so.
